### ISSUE TITLE
Material Design Tabs mode Landscape Forced closed appear

### ISSUE THREAD

**Issue by qferiz** [Suleiman19/Android-Material-Design-for-pre-Lollipop#2]
Material Design Tabs mode Landscape Forced closed appear.
I'm tested on devices OS Android 4.2.2 (API 17).

Logcat info :

06-07 23:33:33.709  28586-28586/com.suleiman.material E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.suleiman.material/com.suleiman.material.activities.TabAnimationActivity}: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment com.suleiman.material.activities.TabAnimationActivity$DummyFragment: make sure class name exists, is public, and has an empty constructor that is public
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2396)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2448)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3965)
            at android.app.ActivityThread.access$700(ActivityThread.java:173)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
            at android.os.Handler.dispatchMessage(Handler.java:107)
            at android.os.Looper.loop(Looper.java:194)
            at android.app.ActivityThread.main(ActivityThread.java:5469)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:857)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment com.suleiman.material.activities.TabAnimationActivity$DummyFragment: make sure class name exists, is public, and has an empty constructor that is public
            at android.support.v4.app.Fragment.instantiate(Fragment.java:432)
            at android.support.v4.app.FragmentState.instantiate(Fragment.java:102)
            at android.support.v4.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:1835)
            at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:266)
            at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:58)
            at com.suleiman.material.activities.TabAnimationActivity.onCreate(TabAnimationActivity.java:33)
            at android.app.Activity.performCreate(Activity.java:5226)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1151)
            at com.lbe.security.service.core.client.b.x.callActivityOnCreate(Unknown Source)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2448)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3965)
            at android.app.ActivityThread.access$700(ActivityThread.java:173)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
            at android.os.Handler.dispatchMessage(Handler.java:107)
            at android.os.Looper.loop(Looper.java:194)
            at android.app.ActivityThread.main(ActivityThread.java:5469)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:857)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.InstantiationException: can't instantiate class com.suleiman.material.activities.TabAnimationActivity$DummyFragment; no empty constructor
            at java.lang.Class.newInstanceImpl(Native Method)
            at java.lang.Class.newInstance(Class.java:1319)
            at android.support.v4.app.Fragment.instantiate(Fragment.java:421)
            at android.support.v4.app.FragmentState.instantiate(Fragment.java:102)
            at android.support.v4.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:1835)
            at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:266)
            at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:58)
            at com.suleiman.material.activities.TabAnimationActivity.onCreate(TabAnimationActivity.java:33)
            at android.app.Activity.performCreate(Activity.java:5226)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1151)
            at com.lbe.security.service.core.client.b.x.callActivityOnCreate(Unknown Source)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2448)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3965)
            at android.app.ActivityThread.access$700(ActivityThread.java:173)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
            at android.os.Handler.dispatchMessage(Handler.java:107)
            at android.os.Looper.loop(Looper.java:194)
            at android.app.ActivityThread.main(ActivityThread.java:5469)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:857)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by Suleiman19** [comment]
Changes have been made and updated accordingly.
Thank you for raising this problem.It's been fixed now.
Issue closed.
